[tool.black]
line-length = 88
target-version = ["py311"]
exclude = '''
(
  /venv
  | /.venv
  | /migrations
)
'''

[tool.isort]
profile = "black"
skip = ["venv", ".venv"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
exclude = "venv|\\.venv|migrations"
